name: Release

on:
  push:
    branches: [ master, develop ]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build and test
        run: ./gradlew build --info

      - name: Upload shadowJar to release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Oraxen ${{ github.ref }}  # Optional: customize release name
          draft: false  # Set to true for draft releases
          prerelease: false  # Set to true for pre-releases
          body: |  # Optional release description
            This is the release for Oraxen version ${{ github.ref }}
          file: build/libs/oraxen-${{ github.ref }}-SNAPSHOT.jar
          asset_name: oraxen-${{ github.ref }}-SNAPSHOT.jar
