# Start of Github Workflow script

# Step 1: Trigger the workflow on a pull request merge event
on:
  pull_request:
    types:
      - opened
      - edited
    # This checks if the pull request has been merged and not just closed
    branches: [master]

jobs:
  # Check if pull request has label
  check-label:
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.pull_request.labels.*.name, 'release')
      && github.event.pull_request.merged == false
    steps:
      - name: Fetch version from gradle.properties
        shell: bash
        run: |
          version=$(grep pluginVersion gradle.properties | awk -F= '{print $2}')
          echo "::set-output name=version::$version"

  # Create new release
  create-release:
    runs-on: ubuntu-latest
    needs: [check-label]
    steps:
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.check-label.outputs.version }}
          release_name: ${{ steps.check-label.outputs.version }}
