name: Publish Release

on:
  push:
    branches:
      - release_workflow

jobs:
  # Determine what version this release is and upload as an artifact
  determine-release-version:
    runs-on: ubuntu-latest

    steps:
      - name: Get version from gradle
        shell: bash
        id: extract_version
        run: |
          version=`gradle properties --no-daemon --console=plain -q | grep "^pluginVersion:" | awk '{printf $2}'`
          echo "::set-output name=pluginVersion::pluginVersion"
      - name: Create release version artifact
        shell: bash
        run: |
          echo "${{ steps.next_version.outputs.version }}" > version.txt
      - name: Upload release version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
