# Start of Github Workflow script

# Step 1: Trigger the workflow on a pull request merge event
on:
  pull_request:
    types:
      - synchronize
    # This checks if the pull request has been merged and not just closed
    branches: [master]

jobs:
  # Check if pull request has label
  check-label:
    runs-on: ubuntu-latest
    if: >-
      (contains(github.event.pull_request.labels.*.name, 'release'))
      && github.event.pull_request.merged == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get plugin version
        id: plugin_version
        shell: bash
        run: |
          version=$(grep "^pluginVersion=" gradle.properties | cut -d'=' -f2)
          echo "::set-output name=version::$version"

      - name: Echo release tag
        run: |
          echo "Release tag: ${{ steps.plugin_version.version }}"
          echo "Release tag2: ${{ steps.plugin_version.outputs.version }}"
      

