name: Release Tag

on:
  push:
    branches:
      - release_workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if pull request was tagged
        run: |
          if [ "$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -E "^TAG_[A-Z0-9]+$")" ]; then
            echo "::set-env name=TAG_NAME::$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -E "^TAG_[A-Z0-9]+$")"
          fi
        id: check_tag

      - name: Get plugin version
        if: env.TAG_NAME
        run: echo "::set-env name=PLUGIN_VERSION::$(grep "^pluginVersion" gradle.properties | awk -F '=' '{ print $2 }')"
        id: get_version

      - name: Create Release Tag
        if: env.TAG_NAME
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PLUGIN_VERSION }}
          release_name: ${{ env.PLUGIN_VERSION }}
          draft: false
          prerelease: false
